import {getLanguage} from '@/utils/globals';
const language = getLanguage();
type TYiiLangKeys = 'pt_BR';

const langFormigo = {
  pt_BR: {
    'Enviar para o n\u00famero informado': 'Enviar para o n\u00famero informado',
    'Enviar para o n\u00famero informado, sem o nono d\u00edgito':
      'Enviar para o n\u00famero informado, sem o nono d\u00edgito',
    feedbackFormInputGroupMaxSizeError: 'A quantidade m\u00e1xima de itens j\u00e1 foi adicionada',
    feedbackFormValidatorCnpjInvalid: 'CNPJ inv\u00e1lido',
    feedbackFormValidatorCpfInvalid: 'CPF inv\u00e1lido',
    feedbackFormValidatorCurrencyInvalid: 'Valor monet\u00e1rio inv\u00e1lido (ex. v\u00e1lido: 1.000,00)',
    feedbackFormValidatorDateHourIncomplete: 'Inclua o hor\u00e1rio ap\u00f3s a data',
    feedbackFormValidatorDateInvalid: 'Data inv\u00e1lida',
    feedbackFormValidatorEmailInvalid: 'E-mail inv\u00e1lido',
    feedbackFormValidatorErrors:
      'O formul\u00e1rio cont\u00e9m erros de preenchimento, verifique indica\u00e7\u00e3o dos erros em cada campo',
    feedbackFormValidatorFloatInvalid: 'Informe somente n\u00fameros (use v\u00edrgula como separador decimal)',
    feedbackFormValidatorHourInvalid: 'Hora inv\u00e1lida',
    feedbackFormValidatorIntegerInvalid: 'Informe somente n\u00fameros',
    feedbackFormValidatorMaxLengthDraftJsError: 'Limite de caracteres excedido',
    feedbackFormValidatorMaxSizeSelectionError: 'A quantidade m\u00e1xima de itens j\u00e1 foi selecionado',
    feedbackFormValidatorMinSizeSelectionError: 'A quantidade m\u00ednima de itens precisa ser selecionado',
    feedbackFormValidatorPasswordWeakError: 'Senha vulner\u00e1vel',
    feedbackFormValidatorPhoneInvalid: 'Telefone inv\u00e1lido',
    feedbackFormValidatorRadioTableColsUniqueError: 'Marque apenas uma op\u00e7\u00e3o por coluna',
    feedbackFormValidatorRadioTableRowsCompleteError: 'Marque todas as linhas com uma op\u00e7\u00e3o',
    feedbackFormValidatorRepeatPasswordError: 'As senhas precisam ser iguais',
    feedbackFormValidatorRequired: 'Preenchimento obrigat\u00f3rio',
    feedbackFormValidatorSelectedOnly: 'Selecione uma op\u00e7\u00e3o da lista',
    feedbackFormValidatorZipCodeInvalid: 'CEP inv\u00e1lido',
    feedbackUnknownError: 'Erro desconhecido',
    fragmentAgeDescDay: 'dia',
    fragmentAgeDescDays: 'dias',
    fragmentAgeDescMonth: 'mês',
    fragmentAgeDescMonths: 'meses',
    fragmentAgeDescYear: 'ano',
    fragmentAgeDescYears: 'anos',
    fragmentEmpty: '[vazio]',
    hintCalendarDateUnavailable: 'Indispon\u00edvel',
    hintFormPasswordStrenghtMeterLength: 'Caracteres',
    hintFormPasswordStrenghtMeterLowercase: 'Uma letra min\u00fascula',
    hintFormPasswordStrenghtMeterNumber: 'Um n\u00famero',
    hintFormPasswordStrenghtMeterSymbol: 'Um caractere especial',
    hintFormPasswordStrenghtMeterTitle: 'Requisitos m\u00ednimos de qualidade da senha',
    hintFormPasswordStrenghtMeterUppercase: 'Uma letra mai\u00fascula',
    hintFormPasswordStrenghtMeterValid: 'Senha v\u00e1lida',
    hintFormProcessing: 'Processando o envio',
    labelCalendarHourary: 'Hor\u00e1rio',
    labelCalendarPickButton: 'Selecionar',
    labelFormAddressBrazilComplement: 'Complemento',
    labelFormAddressBrazilLine1: 'Endere\u00e7o',
    labelFormAddressBrazilLine2: 'Bairro',
    labelFormAddressBrazilNumber: 'N\u00ba',
    labelFormAddressBrazilZipCode: 'CEP',
    labelFormAddressCity: 'Cidade',
    labelFormAddressCountry: 'Pa\u00eds',
    labelFormAddressOtherCountryComplement: 'Apartamento, bloco, edif\u00edcio, andar, ...',
    labelFormAddressOtherCountryLine1: 'Rua\/avenida, n\u00famero, caixa postal, ...',
    labelFormAddressOtherCountryLine2: 'Estado\/Regi\u00e3o',
    labelFormAddressOtherCountryZipCode: 'C\u00f3digo postal',
    labelFormCancelButton: 'Cancelar',
    labelFormDeleteButton: 'Excluir',
    labelFormDeleteConfirmCancelButton: 'Cancelar',
    labelFormDeleteConfirmDeleteButton: 'Excluir',
    labelFormInputGroupAddButton: 'Adicionar',
    labelFormPhoneGroupExtension: 'Ramal (se houver)',
    labelFormPhoneGroupMain: 'Principal',
    labelFormPhoneGroupRestrict: 'Restrito',
    labelFormPhoneGroupType: 'Tipo',
    labelFormPhoneGroupWhatsapp: 'Whatsapp',
    labelFormRateVeryBad: 'Muito ruim',
    labelFormRateVeryGood: 'Muito bom',
    labelFormSubmitButton: 'Salvar',
    labelFormTextAreaCounter: 'Caracteres restantes',
    placeholderFormAddressBrazilComplement: 'Apartamento, bloco, edif\u00edcio, andar, ...',
    placeholderFormAddressBrazilLine1: 'Rua, avenida, pra\u00e7a, ...',
    placeholderFormPhoneInputDialingCodePicker: 'Selecione o DDI',
    placeholderQuickSearch: 'Busca r\u00e1pida',
    textFormAddressManualFillInfo: 'Endere\u00e7o n\u00e3o encontrado, por favor preencha os campos manualmente',
    textFormComboBoxHasEmptyid: 'N\u00e3o selecionado da lista',
    textFormComboBoxNotFound: 'Nenhum registro encontrado',
    textFormDeleteConfirmAsk: 'Tem certeza que deseja excluir este registro?',
    textFormDeleteConfirmTitle: 'Confirma\u00e7\u00e3o de exclus\u00e3o',
    textNo: 'N\u00e3o',
    textPhoneContact: 'Contato',
    textPhoneHome: 'Residencial',
    textPhoneMobile: 'Celular',
    textPhoneWork: 'Comercial',
    textRemove: 'Remover',
    textYes: 'Sim',
  },
};
type TYiiLangFormigoMessageKey = keyof typeof langFormigo.pt_BR;
const formigo = (messageKey: TYiiLangFormigoMessageKey) => langFormigo[language as TYiiLangKeys]?.[messageKey] || '';

export default {formigo};
